# Generated by Django 5.2.1 on 2025-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
